### ISSUE TITLE
Summary output does not includes all the time steps

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-common#118]
I think some changes between May 12th (not exactly) and previous release causes the problem. 

Basically, you will not get the results from all the time steps. For example, you specifies 300 days in the deck, you can only read out 280 or 250 days of result from the summary files. And it is a little random. 

I am not sure changes in which module cause this problem, so I just put here. 

Please help to confirm and fix it if verified.

**Comment by andlaus** [comment]
This is a known issue. it was traded for correct well totals here:

OPM/opm-output#12

basically this is caused because it is currently impossible for the `EclipseWriter` to determine when results must be written and when not i.e., if adaptive time stepping is used or not. I suppose the fix for that is not very hard, but it will either require some additional parameters for `EclipseWriter` (which is -- frankly -- inelegant because nobody can complain that this class currently is lacking in terms of complexity) or some refactoring of the time stepping code (which may run into philosophical issues).

**Comment by jokva** [comment]
On that note, all output is under **heavy** review right now and we're very open for improvement suggestions & wishes when it comes to the interface.

**Comment by totto82** [comment]
I really think this must be fixed. Even thought it requires an inelegant solution that run into philosophical issues.

**Comment by andlaus** [comment]
I guess the deeper issue is only partially output code. Rather, IMO the interaction between the simulator and the output code has issues...

**Comment by GitPaean** [comment]
> This is a known issue. it was traded for correct well totals here:

Thanks for the reply. I wish I saw this earlier. 

While for a simulation with total 20 years, I can only get the result at 15 years, which is not right in my opinion.

**Comment by jokva** [comment]
>I guess the deeper issue is only partially output code. Rather, IMO the interaction between the simulator and the output code has issues...

It has. The adaptive time stepping facilities too don't really carry enough information to pass to opm-output, and I have yet to figure out a nice way to handle that.

**Comment by andlaus** [comment]
> I really think this must be fixed. Even thought it requires an inelegant solution that run into philosophical issues.

I'll do this, but we first need to agree on whether the ugly solution which does not require simulator changes or the always-use-adaptive-time-stepping approach should be used. (I'd prefer the latter, but I don't really have strong feelings about this.)

> While for a simulation with total 20 years, I can only get the result at 15 years, which is not right in my opinion. 

yeah, that's sounds quite wrong. do you look at the actual time in the summary file or do you look at the timestep number?

**Comment by GitPaean** [comment]
> yeah, that's sounds quite wrong. do you look at the actual time in the summary file or do you look at the timestep number?

I looked at both. Did not find obvious rules. It can be results more than one report step is missing.

**Comment by andlaus** [comment]
> I looked at both. Did not find obvious rules. It can be results more than one report step is missing. 

weird for which deck did this happen? I tested OPM/opm-output#12 for Norne and it seemed fine...

**Comment by GitPaean** [comment]
I tried SPE1CASE1 in opm-data. 

The results from OPM running gives the time until 2645 days. The Eclipse results give 3650 days.

**Comment by GitPaean** [comment]
> The results from OPM running gives the time until 2645 days. The Eclipse results give 3650 days.

It is kind of random, another running gives results until 2524 days. a new running gives results until 2614 days.

**Comment by andlaus** [comment]
what happens if you run `flow` on that with `full_timestep_initially=true`?

**Comment by GitPaean** [comment]
Just from OPM/opm-data#106

This deck is not supported by OPM due to keyword DRSDT.  I will test with other cases.

**Comment by andlaus** [comment]
well, yes. but the schedule should be not affected by this. what does the terminal output say? (i.e., is the summary file consistent with that?)

**Comment by GitPaean** [comment]
The terminal output show the correct time stepping information. 

The one read from summary files are showing weird information.

**Comment by andlaus** [comment]
ok. I just ran that case myself: it seems like the last timestep is not written (alternatively, the results are off-by-one):

```
> ./bin/flow ~/opm-data/spe1/SPE1CASE1.DATA
[...]
> summary.x SPE1CASE1 WOPT:PROD | tail -n3
3224.00   30/10/2023        4.91017e+07 
3254.00   29/11/2023        4.93058e+07 
3285.00   30/12/2023        4.95135e+07
```

it is still a long shot from 2524 days though...

**Comment by GitPaean** [comment]
Yes and No. It is a little random. and your result is lacking more than 10 report steps.

**Comment by andlaus** [comment]
I had a closer look: it seems like the results are off-by-one: the reported values correspond to the end of a report step, while their times is the beginning. fixing this would be quite easy (add dt), but most likely there won't be a value for the initial solution anymore...

**Comment by andlaus** [comment]
> and your result is lacking more than 10 report steps. 

it is exactly one year. (that's suspicious.) maybe it's a bug in the opm-parser schedule code...

**Comment by GitPaean** [comment]
It is a little random, maybe there is some leaking or undefined behavior, I do not know. 

If you would like you can try polymer_test_suite/simple2D in opm-data. 

For different running, summary files contain different total time span.

**Comment by andlaus** [comment]
hm. the debug messages are quite confusing. I have a hunch that this could be caused by the asynchronous output changes. This would also explain the non-deterministic behavior which you (and, to a lesser extend, I) see.

@dr-robertk: is this possible? (i.e. are there any measures to prevent concurrent access to the memory which is written?) also, is there an easy way to disable the asynchronous output?

**Comment by atgeirr** [comment]
I believe async_output=false should do the trick.

**Comment by GitPaean** [comment]
> I believe async_output=false should do the trick.

It looks like `async_output=false` might recover the summary output.

**Comment by andlaus** [comment]
> It looks like `async_output=false` might recover the summary output. 

I can confirm that. (actually this is bad news because it means that there's the possibility of a fundamental problem in the asynchronous output code...)

**Comment by GitPaean** [comment]
`async_output` was defaulted to be `false` for last release.  Maybe we can make it default to be `false` for now again.

**Comment by alfbr** [comment]
As a stop gap solution, but we should really fix it. Threading output really makes a performance impact over here.

**Comment by andlaus** [comment]
I guess for async output to work correctly, all arrays need to be copied before they're written to disk and a lock which prevents concurrent writes needs to be introduced. Maybe this has a performance impact as well, maybe it doesn't...

**Comment by joakim-hove** [comment]
![image](https://cloud.githubusercontent.com/assets/1321665/15359143/467ef57e-1d08-11e6-9ce9-b9eb1207fe34.png)

As @jokva has already indicated the output writing facilities is under massive massive refactoring at the moment. It is in my opinion **not** worth the effort to fix anything remotely close to properly in the current outputwriter. If async is identified as the problem - async should be disabled, and the case closed. To do anything more is to "carry oat to a dead horse".

**Comment by atgeirr** [comment]
Since this problem may be preventing Jenkins etc. from providing correct results, I agree that we should change the default until the problem is fixed. For work that does not require the output to be correct, one may enable it on the command line.

**Comment by alfbr** [comment]
> As @jokva has already indicated the output writing facilities is under massive massive refactoring

That should be accompanied with a time estimate, are PRs just around the corner?

**Comment by jokva** [comment]
Not really, there is a **substantial** amount of work to fix the problems that have accumulated over time. I didn't manage until today to resolve the opm-core/opm-output circular dependency, and to accomplish that I had to disable adaptive time stepping output *and* VTK output (which must be slightly rewritten anyway).

Thing is, enabling async output once the new opm-output is implemented should be trivial, but simulators are pretty heavy to change due to the tentacular architecture.

How fast that happens really comes down to how much breaking we're tolerating. Less breakage means slower development. I'd say two weeks minimum.

**Comment by blattms** [comment]
BTW The problem seems to be on the simulator side and IMHO totally unrelated to opm-output. The problem is that for each writeTimeStep call a new async (thread) is started without any regard on the write order. This will only work correctly if the last call already finished before the new async is created. Basically different asyncs may write to the same files at the same time, later time steps might have been written before the one that is currently written, etc.

**Comment by atgeirr** [comment]
What is the overall status on summary output, do we get it for ministeps now? Is it controlled by the deck input, or are there changes required to the simulator to enable it? Perhaps @jokva or @joakim-hove can shed light on this?

I assume and hope the system has been so much improved by now that this can be closed.

About the async problem pointed out by @blattms: how should we attack this?

**Comment by bska** [comment]
@GitPaean : Is this issue still relevant?  If not, we should close it.

**Comment by GitPaean** [comment]
> @GitPaean : Is this issue still relevant? If not, we should close it.

We should probably close it.
