### ISSUE TITLE
Bug in TimeMap.cc

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-common#1206]
Issue in nynorsk from @atgeirr:
```
 Hei!

Køyrer ein prediksjonscase med opptil 1-år lange rapportsteg, og RPTRST 
som seier BASIC=5 FREQ=6 (output kvar 6. mnd).

Start er på steg 339, 1. mai 2019.

Får berre restart for steg 341 (1. oktober 2019)  og 347 (1. september 2020). 
Rapportstega frå nummer 352 av er alle saman 1. januar påfølgande år.

Bug funne: TimeMap.cpp linje 131-132.

Atgeirr
```

**Comment by bska** [comment]
Are the [`nw`](https://github.com/OPM/opm-common/blob/1d95cd8248af9aff27e46cbc170ba6b3ef1df5fe/src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp#L122) and [`last`](https://github.com/OPM/opm-common/blob/1d95cd8248af9aff27e46cbc170ba6b3ef1df5fe/src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp#L123) timestamps correct here?  If not, then this is probably related to my somewhat rushed commit 428d4c41f (PR #1107).  Otherwise, do `nw` and `last` happen to have the same month but different years?  If so, then we **probably** need to check the year field too when [determining](https://github.com/OPM/opm-common/blob/1d95cd8248af9aff27e46cbc170ba6b3ef1df5fe/src/opm/parser/eclipse/EclipseState/Schedule/TimeMap.cpp#L131) if this is a new month.

**Comment by joakim-hove** [comment]
> If so, then we probably need to check the year field too when determining if this is a new month.

I think this is the problem.

**Comment by bska** [comment]
Is this still a problem following #1209 being merged into master?  If not, I suggest we close the issue.
