### ISSUE TITLE
not able to build opm-common on mac 

### ISSUE THREAD

**Issue by miroine** [OPM/opm-common#1610]
Hei ... try to build opm-common but got some issues .. any one can help. ?
```
[ 15%] Building CXX object CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/Python/Python.cpp.o
In file included from /Users/miroine/project_developments/repos/opm-common/src/opm/parser/eclipse/Python/Python.cpp:21:
/Users/miroine/project_developments/repos/opm-common/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp:298:33: error: 
      no matching member function for call to 'splitDynMap'
            auto splitvfpprod = splitDynMap(vfpprod_tables);
                                ^~~~~~~~~~~
/Users/miroine/project_developments/repos/opm-common/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp:452:9: note: 
      candidate template ignored: substitution failure : template template
      argument has different template parameters than its corresponding template
      template parameter
        splitDynMap(const Map<Key, Opm::DynamicState<Type>>& map)
        ^
/Users/miroine/project_developments/repos/opm-common/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp:301:32: error: 
      no matching member function for call to 'splitDynMap'
            auto splitvfpinj = splitDynMap(vfpinj_tables);
                               ^~~~~~~~~~~
/Users/miroine/project_developments/repos/opm-common/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp:452:9: note: 
      candidate template ignored: substitution failure : template template
      argument has different template parameters than its corresponding template
      template parameter
        splitDynMap(const Map<Key, Opm::DynamicState<Type>>& map)
        ^
2 errors generated.
make[2]: *** [CMakeFiles/opmcommon.dir/src/opm/parser/eclipse/Python/Python.cpp.o] Error 1
make[1]: *** [CMakeFiles/opmcommon.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by bska** [comment]
> try to build opm-common but got some issues

Are you by any chance using a compiler other than GCC and/or a standard library other than libstdc++?

I **think** the reason you're getting a build failure is that the `splitDynMap` [function](https://github.com/OPM/opm-common/blob/438e4b68bfbbafe679f0c23783bd87f0f1bb4f47/opm/parser/eclipse/EclipseState/Schedule/Schedule.hpp#L452) that was introduced in @akva2's commit 26b2a3a5 (PR #1565) isn't really a match for the `vfpprod_tables` and `vfpinj_tables`.  The latter two are of type `std::map` with defaulted comparison operators and allocators and that doesn't really match the declared type
```C++
template <class, class> Map
```
needed by the `splitDynMap` member function.

The `splitDynMap` **does** however match Opm's [`OrderedMap`](https://github.com/OPM/opm-common/blob/438e4b68bfbbafe679f0c23783bd87f0f1bb4f47/opm/parser/eclipse/EclipseState/Util/OrderedMap.hpp#L31-L32) type which is why you don't see  diagnostic messages for the other calls to `splitDynMap`.

**Comment by akva2** [comment]
i'll fix it. gcc is more forgiving with templates with default parameters.
