### ISSUE TITLE
Error with RawString initializer list

### ISSUE THREAD

**Issue by ducbueno** [OPM/opm-common#1869]
Anyone else getting this error on build?

```
opm-common/src/opm/parser/eclipse/Parser/ParserItem.cpp:466:61: error: no matching function for call to ‘Opm::RawString::RawString(<brace-enclosed initializer list>)’
                 auto raw_string = RawString{ token.string() };
```

The error also occurs in line 519.

**Comment by atgeirr** [comment]
I do not get this error usually, but if I intentionally force the compiler to use C++14 rather than C++17, then I get it, too. So I believe this is probably caused by your cmake compiler settings asking for C++14. OPM requires C++17, and this should be chosen automatically, unless you manually override it in a cache file (as in running cmake with `cmake -C cachefile.cmake <other arguments>`).

If you run `make VERBOSE=1` it should print the actual compile and link commands used, look for `-std=c++XX` in the compile command that fails. (Note that it may occur twice.) The `XX` should be either `17` or `1z` to give c++17. If it is `11`, `14`, `1x`or `1y` it is wrong.

**Comment by ducbueno** [comment]
Thank you @atgeirr ! That was it.

I'm building OPM in a slightly older machine with Ubuntu 16 and g++ default version was 5.4.0. 

The problem was gone by updating g++ to 9.3.0.

**Comment by ducbueno** [comment]
Now I'm getting an error building opm-material......

```
In file included from /usr/include/dune/common/stdstreams.hh:16,
                 from /usr/include/dune/common/parallel/mpihelper.hh:13,
                 from /home/rodolfo/eduardo/opm/opm-material/tests/test_immiscibleflash.cpp:49:
/usr/include/dune/common/debugstream.hh:345:16: error: ISO C++17 does not allow dynamic exception specifications
  345 |     void pop() throw(DebugStreamError) {
      |                ^~~~~
/usr/include/dune/common/debugstream.hh:377:19: error: ISO C++17 does not allow dynamic exception specifications
  377 |     void detach() throw(DebugStreamError) {
      |                   ^~~~~
/usr/include/dune/common/debugstream.hh:389:36: error: ISO C++17 does not allow dynamic exception specifications
  389 |     void tie(DebugStreamState& to) throw(DebugStreamError) {
      |                                    ^~~~~
/usr/include/dune/common/debugstream.hh:403:18: error: ISO C++17 does not allow dynamic exception specifications
  403 |     void untie() throw(DebugStreamError) {
      |                  ^~~~~
```

What can be causing that?

**Comment by bska** [comment]
> ```
> void pop() throw(DebugStreamError) {
> ```

Are you by any chance using Dune 2.5.0 or earlier?  If you are I'd recommend getting 2.6.0 or maybe 2.7.0.  The exception specifications are no longer there in Dune 2.6.0.

**Comment by blattms** [comment]
@ducbueno please close with a comment if this is resolved.

**Comment by ducbueno** [comment]
Problem solved. Sorry for not commenting before.
