### ISSUE TITLE
DUNE_ISTL_VERSION_* not set in opm-simulators.

### ISSUE THREAD

**Issue by dr-robertk** [OPM/opm-common#190]
I'm having the problem that the version of istl is not set in config.h
This has worked before, and I did not change the DUNE version. What could be the reasons and where are these variables set?

Here a snippet from config.h : 

#define DUNE_GRID_EXPERIMENTAL_GRID_EXTENSIONS 1
#define DUNE_GRID_VERSION_MAJOR 2
#define DUNE_GRID_VERSION_MINOR 4
#define DUNE_GRID_VERSION_REVISION 1
#define DUNE_COMMON_VERSION_MAJOR 2
#define DUNE_COMMON_VERSION_MINOR 4
#define DUNE_COMMON_VERSION_REVISION 1
/* #undef DUNE_ISTL_VERSION_MAJOR */
/* #undef DUNE_ISTL_VERSION_MINOR */
/* #undef DUNE_ISTL_VERSION_REVISION */

**Comment by blattms** [comment]
Works for me with a fresh build and current master

**Comment by dr-robertk** [comment]
Which DUNE version?

**Comment by blattms** [comment]
2.4.1

**Comment by dr-robertk** [comment]
Hm strange. I'll test with a fresh build also. Just in case, which cmake version?

**Comment by akva2** [comment]
same here, i cannot reproduce, i cannot fix. opm-simulators gets the versions set as requested from its CMakeLists.txt, opm-grid does not since it is not requested  (see the config hook in CMakeListst.txt to see the how). i run dune 2.4.1 from xenial repos, and it also builds fine against the 2.3 on jenkins. i have new cmake locally, jenkins has older cmake so i thought i had the whole test matrix covered.

**Comment by blattms** [comment]
cmake version 3.0.2

@akva2 Where do these variable get set up in the cmake scripts? I could not find the place. Must be magic.

**Comment by akva2** [comment]
which variables ? you mean the versions ? it works like this;
1) individual find modules set the cmake variables [module]_VERSION_XXX. this is achieved for dune modules through the macro find_dune_version from UseDuneVer.cmake. this is is overly complicated, in large parts due to my favorite build wrapper, but basically it extracts the versions from the dune.module file and sets the cmake variables accordingly.

2) the opm_need_version_of() macro calls from the config hook then adds them to the config vars (stuff written to config.h)

**Comment by GitPaean** [comment]
Just FYI. The master compiles okay with Dune 2.4.1 and cmake 3.5.1 from  my side.

**Comment by dr-robertk** [comment]
A fresh opm chain works for me too. Sorry for the noise.

**Comment by dr-robertk** [comment]
Thanks for the feedback.

**Comment by atgeirr** [comment]
Does that mean #188 should be closed as well?
