### ISSUE TITLE
2021-10 Command Line Parameters

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#2846]
Command line parameter changed from `--linear-solver` to `--linsolver`

Functionality is the same as before.

Was this intentional or a typo?

**Comment by atgeirr** [comment]
This happened a while ago, and it was intentional, I wanted a shorter name. I must admit I regret it now, perhaps we should change it back? I do think it had LOTS of functionality change though, including the ability to specify a JSON file configuring the linear solver, that eliminated some other command line parameters.

**Comment by OPMUSER** [comment]
I asked this in case it was a typo, so we could correct it for the 2021-10 release both in the code and the manual. The code and the manual are consistent for the 2021-10 release.

I only check the command line parameters once when RC1 is out, so I don't waste time performing multiple updates. If you want to to revert or keep as is, that is okay with me, I'll pick up any changes for the 2022-04 release.

Will close this now.
