### ISSUE TITLE
What is data::Connection::m_perf_range and how is it used for output?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#2921]
During the last year this became a `std::optional` which contradicts some of my previous assumptions when writing output data. Namely, that `data::Connection` to be simple contiguous struct without any pointers that can be written to a char array. Unfortunately, `std::optional` most probably uses a pointer somewhere inside.

I am assuming that during parallel output `m_perf_range` will contain rubbish for distributed wells at least.

Hence:  What is it (the documentation :wink: isn't really clear)? Is this used/written for output. For all wells or just standard ones?

Changeset is 8b70e42e0fb6f. the code before that change hints that this connected to MS well, That got lost, too.

**Comment by joakim-hove** [comment]
syd::optional does not allocate om the dere store but has an inplace buffer - I think it uses something like inplace new to actuslly assign valeu🤔

Anyway - I Will check an fet back to your real question

**Comment by blattms** [comment]
Any news?

**Comment by bska** [comment]
> Any news?

I'm just revisiting this area in a different context and I think there's **some** amount of confusion in the original question.  The [`data::Connection`](https://github.com/OPM/opm-common/blob/cc49bd15faacff3ee5a2a8d8d9a71c3fe3605ade/opm/output/data/Wells.hpp#L197) type **does not** have an `m_perf_range` data member, but the [`Opm::Connection`](https://github.com/OPM/opm-common/blob/cc49bd15faacff3ee5a2a8d8d9a71c3fe3605ade/opm/input/eclipse/Schedule/Well/Connection.hpp#L43) type [does](https://github.com/OPM/opm-common/blob/cc49bd15faacff3ee5a2a8d8d9a71c3fe3605ade/opm/input/eclipse/Schedule/Well/Connection.hpp#L243) have that data member.  It's a very easy mistake to make and we should probably rename at least one of these types in order to reduce the risk of mistaken identity.

> contradicts some of my previous assumptions when writing output data. Namely, that `data::Connection` to be simple contiguous struct without any pointers that can be written to a char array.

That was true until fairly recently, but then we added support for traces to the [`data::Rates`]() class which turned the object from a simple POD structure into a variable-length object with a non-trivial copy constructor &c (PR #2468, commit 94c6c4942c).  That particular aspect possibly prevents using `MPI_gatherv()`&mdash;or a wrapper thereof&mdash;as a mechanism for communicating connection-level output information between ranks sharing a well.  I don't know if it is possible to leverage the MPI serialiser to perform this task given that `data::Connection` implements the [`serializeOp()`](https://github.com/OPM/opm-common/blob/cc49bd15faacff3ee5a2a8d8d9a71c3fe3605ade/opm/output/data/Wells.hpp#L232) protocol.

In the short term we can probably revert `data::Rates` back to a POD object by pulling the tracer-related quantities out to the [`data::Well`](https://github.com/OPM/opm-common/blob/cc49bd15faacff3ee5a2a8d8d9a71c3fe3605ade/opm/output/data/Wells.hpp#L408) object.  The reason is that we presently report tracer quantities only at the well level.  Long term however, we probably want to support reporting those quantities at the connection and level too so we will have to contend with some kind of variable-length information here in the future.

**Comment by blattms** [comment]
Yeah, I did not see that one (storing a std::map<string, bla> for each connection) coming. Hopefully, I am mistaking, but it seems we store such a map for each connection. Are the size and keys of this map really varying from connection to connection?

If not, it might make a lot of sense storing this mapping once external to this class and use a simple vector for storage. Might save quite some space/bandwidth.

**Comment by bska** [comment]
> Hopefully, I am mistaking, but it seems we store such a map for each connection.

We do indeed do that.  There is one `data::Rates` object for each `data::Connection` and, therefore, one such map for each connection result object.

> Are the size and keys of this map really varying from connection to connection?

In principle, yes.  As of right now, no.  As alluded to earlier, the tracer result map is **always** empty at the connection level now, but there might indeed be a different number of tracer results for each connection in the future.

> it might make a lot of sense storing this mapping once external to this class and use a simple vector for storage. Might save quite some space/bandwidth.

I think that makes sense in general though.  I'd **really** like for `data::Rates` to go back to being a POD.  Putting that map into `data::Rates` has increased the communication complexity a lot in other places.
