### ISSUE TITLE
WCONHIST Warning

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#3075]
Client model has numerous messages of the form:
```
Warning: LIQ preferred phase not supported for well 7RO040, using OIL instead
```
I don't see a `WHISCTL` keyword that would change the control from LIQ to OIL in either OPM Flow or E100 input decks and both simulators give the same liquid profile.

So is this message wrong, if so I'll try and find it and fix it?

**Comment by bska** [comment]
The message is, sadly, correct.  Flow does not support using `LIQ` as a well's preferred phase in `WELSPECS`.   This is a long-standing bug/omission in the simulator stemming from a somewhat naive internal notion of phases so we don't have an entry for a liquid phase, only for the distinct oil and water phases.  For producing wells this **mostly** matters if you plot the `WPI` summary vector (productivity index for well's preferred phase).  In the current treatment `WPI` will not have contributions from the water phase if the declared preferred phase is `LIQ`.  For injecting wells `WELSPECS`'s preferred phase doesn't really matter at all since the preferred phase is (typically) reset to the injected phase in `WCONINJE`/`WCONINJH` anyway.

**Comment by OPMUSER** [comment]
Closing, as answered.
