### ISSUE TITLE
RPTRST: Is the PBPD Option Supported?

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#3153]
For the RPTRST keyword, is the PBPD  option that outputs the bubble point and dew point pressures supported? There is no warning message indicating it is not, but the data is missing from the restart file.

**Comment by bska** [comment]
> is the PBPD option that outputs the bubble point and dew point pressures supported?

Sort of.  This is a long-standing problem in Flow's support for outputting 3D vectors to the restart file.  Due to very early design decisions in the output system we distinguish between those vectors which are needed for restart and those which are "merely" for visualisation and analysis.  This classification is imperfect however which leads to potentially outputting vectors that are incompatible with ECLIPSE such as `TEMP` in a non-thermal simulation run.

If you're willing to forego the ability to restart ECLIPSE from a Flow simulation run, e.g., simulating the historic period using Flow and the prediction period using ECLIPSE, then you can get a richer set of 3D vector output including the `PBUB` and `PDEW` vectors generated by the `PBPD` option by passing the
```
--enable-opm-rst-file=true
```
command line option.

**Comment by bska** [comment]
For what it's worth, I've been meaning to address this incorrect taxonomy for quite a while, but it's never been important enough to percolate to the top of the list of priorities.

**Comment by OPMUSER** [comment]
Thanks for the clarification, that works. I'll add note to the manual. Would be nice to fix this when we get time. Note, there is always the restart file HIDDEN keyword that might be an option. 

Closing as issue resolved.
