### ISSUE TITLE
2022-10 pre: Error when adding 0 to WELLDIMS

### ISSUE THREAD

**Issue by goncalvesmachadoc** [OPM/opm-common#3194]
If user has:
![image](https://user-images.githubusercontent.com/54812829/198080373-01aa004c-61ab-4316-816f-9f7c4bef77f5.png)
Flow give this error:
![image](https://user-images.githubusercontent.com/54812829/198080415-611acff4-62d1-4900-9295-7ed3aa24325d.png)

**Comment by bska** [comment]
Thank you for the report.  I'm a little confused by the statement

> nothing is output to EGRID.

because my initial hunch is that the message is triggered by Item 11 ([maximum number of well-lists per well](https://github.com/OPM/opm-common/blob/2bbbef51908a76c193353b67a8f6d3a28c7b6de7/src/opm/input/eclipse/share/keywords/000_Eclipse100/W/WELLDIMS#L73-L78)) being zero.  That would, however, mostly affect the restart file instead of the EGRID file.  Does the model create an EGRID file at all?  If not, do you get one if you add
```
GRIDFILE
  1* 1 /
```
to the `GRID` section?

In any case, does setting Item 11 to a positive value&mdash;say the default value 1&mdash;allow the simulation to go further?  If it does, then I know what's wrong and I think we can fix it rather quickly.

**Comment by goncalvesmachadoc** [comment]
Let me check.

**Comment by goncalvesmachadoc** [comment]
Yes, EGRID is there and setting item 11 to 1 solves the issue.

**Comment by bska** [comment]
> Yes, EGRID is there and setting item 11 to 1 solves the issue.

Okay, that's good to know.  Would you mind checking one more thing, please?  Does the model use the `WLIST` keyword at all?  If not, this is "just" a bug in the restart file output code which by accident we did not hit before.

**Comment by goncalvesmachadoc** [comment]
There is no WLIST keyword.

**Comment by bska** [comment]
> There is no WLIST keyword.

Thanks a lot, that's really good to know.  Then we "just" need to add some checks in a few critical locations to handle that situation.

**Comment by goncalvesmachadoc** [comment]
Hope "just" is just a just. :smile:
