### ISSUE TITLE
remove dune-control support

### ISSUE THREAD

**Issue by akva2** [OPM/opm-common#36]
dune-control support is a useless hack and maintaining support is additional load on the build system. 

let's remove this.

**Comment by bska** [comment]
> maintaining support [for `dunecontrol`] is additional load on the build system.

Clearly.  On the other hand I'd appreciate it if we all could refrain from divisive characterisations such as "cancer".

**Comment by dr-robertk** [comment]
@akva2: Ok. But only if the sibling stuff goes too. I'm using dune-control and to that date it works fine and is the only way that works to build the OPM modules. I'm pretty sure that when I follow the instructions on the OPM web site, that I won't be able to build OPM. Until then, let's keep it.

**Comment by bska** [comment]
> I'm using dune-control and to that date it works fine and is the only way that works to build the OPM modules.

That statement is not true--at least not literally.  I'm building all of OPM in many different configurations and I don't use `dunecontrol`.

**Comment by atgeirr** [comment]
> But only if the sibling stuff goes too.

Please don't take hostages...

Dune-control support and sibling builds will remain for the time being since we have not yet reached a consensus about a single proper way to build. 



> I'm pretty sure that when I follow the instructions on the OPM web site, that I won't be able to build OPM

That has (unfortunately) been true since we introduced opm-cmake. However they have been tested (by people here coming into the project) successfully a few times. I will update the instructions when opm-common is ready.

**Comment by andlaus** [comment]
I'm using dunecontrol all the time. I would not mind if support for it was removed though, if I had an adequate alternative to rebuild everything with different options in one go.

**Comment by dr-robertk** [comment]
I investigated this topic a bit and it turns out that everything works fine when DuneCompat.cmake is removed (DUNE 2.4 with cmake). The configure script in cmake/Scripts is not needed anymore, because dunecontrol calls cmake directly and also not need is the DuneCompat2.cmake. There is a minor issue in dunecontrol that is being fixed as we "speak". 

The only problem I see, is, that this would require to use the latest release version,  DUNE version 2.4. But it might take the OPM community another decade or so to upgrade to 2.4.....

**Comment by atgeirr** [comment]
> The only problem I see, is, that this would require to use the latest release version, DUNE version 2.4. But it might take the OPM community another decade or so to upgrade to 2.4.....

I don't think so: we can probably leapfrog to 2.4 at some point instead of going through 2.3. @alfbr?

**Comment by atgeirr** [comment]
> Dune-control support and sibling builds will remain for the time being since we have not yet reached a consensus about a single proper way to build.

This I said a while ago, and I will therefore close this issue. However:

> I investigated this topic a bit and it turns out that everything works fine when DuneCompat.cmake is removed (DUNE 2.4 with cmake). The configure script in cmake/Scripts is not needed anymore, because dunecontrol calls cmake directly and also not need is the DuneCompat2.cmake. There is a minor issue in dunecontrol that is being fixed as we "speak".

Therefore: when we are on Dune 2.4 we should revisit and simplify a bit (removing the configure script etc.), but for now this is a non-issue.
