### ISSUE TITLE
Problem with the keyword EQUIL

### ISSUE THREAD

**Issue by anaxsouza** [OPM/opm-common#3662]
I'm having problem with the keyword `EQUIL`, getting this error:
```
Error: Problem with keyword EQUIL
In base_bl.data line 139.
Internal error: Malformed floating point number 'SUMMARY'

Error: Unrecoverable errors while loading input: Problem with keyword EQUIL
In base_bl.data line 139.
Internal error: Malformed floating point number 'SUMMARY'`
```
I don't know how to solve even reading the manual. I'm leaving my code and the outputs.
[base_bl.txt](https://github.com/OPM/opm-common/files/12514383/base_bl.txt)
[BASE_BL.txt](https://github.com/OPM/opm-common/files/12514386/BASE_BL.txt)
[BASE_BL2.txt](https://github.com/OPM/opm-common/files/12514387/BASE_BL2.txt)

**Comment by bska** [comment]
> ```
> Error: Problem with keyword EQUIL
> In base_bl.data line 139.
> Internal error: Malformed floating point number 'SUMMARY'
> ```

I apologise for the poor diagnostic message.  When you get this message, the simulator is in a very confused state.  It expected to find a floating-point number, but found the string `SUMMARY`&ndash;a sectioning keyword&ndash;instead.  We really should be able to generate a better diagnostic message here.

Anyway, your `EQLDIMS` keyword has the following entries
> ```
> --          MAX         MAX         RSVD        TVDP        TVDP
> --          EQLNUM      DEPTH       NODES       TABLE       NODES
> EQLDIMS
>             9           1*          20          1*          1*      /
> ```
and, in particular, the first item (`EQLDIMS(1)` with the numerical value 9) dictates the number of records that's expected in the `EQUIL` keyword.  On the other hand, your `EQUIL` keyword is set up as follows
> ```
> --      R.P.D.     R.D.P.     D. O-W C.     P. O-W C. R.    D. C. O-W       P.R.C
> EQUIL
>         0          14.7       0.328084      0               0               0           0 0 0 
> /
> ```
which has exactly one record.  Since `EQLDIMS(1)` must match the number of records in `EQUIL`, you have two options

1. Reduce item 1 of `EQLDIMS` to match the number of records (1) in `EQUIL`
2. Increase the number of records in `EQUIL` to match the declared number of equilibration regions from `EQLDIMS` (9).

If you don't need 9 equilibration regions I suggest using the first option here.

**Comment by anaxsouza** [comment]
It solved my problem, Thank you so much!
