### ISSUE TITLE
Can not load restart file in ResInsight

### ISSUE THREAD

**Issue by totto82** [OPM/opm-common#581]
I get the following message when I try to load a model into ResInsight
```
Error message: __hash_get_node_unlocked: tried to get from key:ICON which does not exist - aborting
```
The case has multi-segmented wells but multi-segmented wells are disabled by the simulator.

**Comment by joakim-hove** [comment]
OK:

1. Can you mail me the restart file - or alternatively just run the command `kw_list.x $RESTART_FILE` where `kw_list.x` is a small utility from libecl (assuming you have built with `-DAPPLICATIONS=ON`)
2. I guess the error message is kind of clear - but it is not clear to mo whether the bug/problem is that Resinsight/libecl *should* have handled a restart file without `ICON`- or alternatively that the problem/bug is with the restart file written by flow which is missing `ICON`

My experience with Eclipse based restart files is that the always (at least if there are completed wells in the model), have the `ICON` keyword, so I guess there are many codepaths which do not check for the `ICON` keyword.

**Comment by joakim-hove** [comment]
@totto82 : I did not find your email. As has been identified by e.g. @tskille and others the final symptom is that several timesteps miss the `ICON` keyword, I guess others are looking into a real fix. However - if you are interested I could help you patch your Resinsight code - that should be a 5 minute job, so that you can load the offending timesteps (allthough they will be without well information).

Contact me on email (joakim.hove _AT_ gmail.com) or telephone if you are interested in that patching.

**Comment by bska** [comment]
All,

This **may** be related to, or at least triggered by, Pull Request #549 which was merged yesterday.  I am trying to reproduce the symptoms locally.
