### ISSUE TITLE
dune-common of Debian jessie not found using dunecontrol

### ISSUE THREAD

**Issue by blattms** [OPM/opm-common#63]
I just wanted to test my code on another server and used jessie's stock dune packages (version 2.3.1) to save time.

Unfortunately, in opm-material dune-common is not found:
```
-- dune-common_ROOT = /usr/lib/x86_64-linux-gnu/cmake/dune-common
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find dune-common (missing: dune-common_INCLUDE_DIR
  dune-common_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /home/mblatt/DUNE/opm-common/cmake/Modules/OpmPackage.cmake:358 (find_package_handle_standard_args)
  /home/mblatt/DUNE/opm-common/cmake/Modules/Finddune-common.cmake:14 (find_opm_package)
  /home/mblatt/DUNE/opm-common/cmake/Modules/OpmFind.cmake:147 (find_package)
  /home/mblatt/DUNE/opm-common/cmake/Modules/OpmFind.cmake:211 (find_and_append_package_to)
  /home/mblatt/DUNE/opm-common/cmake/Modules/OpmLibMain.cmake:104 (find_and_append_package_list_to)
  CMakeLists.txt:95 (include)


-- Configuring incomplete, errors occurred!
```

The problem is that dunecontrol defines dune-common_ROOT and opm then always uses NO_DEFAULT_PATH in its find_... calls

**Comment by akva2** [comment]
sigh. i'll get to it eventually.

**Comment by akva2** [comment]
there must be more to this. I

1) set up a fresh jessie vm (debian-8.2.0-amd64-netinst.iso, xfce desktop).
2) installed system-level dependencies (boost, compilers, cmake, dune)
3) installed ert manually
4) cloned opm-[common|parser|core|autodiff|material] and dune-cornerpoint in ~/opm, pointing to the master branches.
5) ran dunecontrol all in ~/opm

and everything built without hassle. i do notice that i forgot blas/lapack so some small things are probably not as they should be in my build, but i doubt that is relevant. also i built with internal eigen3.

as for dropping common paths when _ROOT is set, this is sort-of standard cmake behavior. to the extent these things are standardized. some modules will consider it as an additional look-here-first path, some will consider it as the one and only path. OPM seems to have gone with the latter interpretation (i haven't looked into the details). in any case setting it should not break anything if it has the proper value, and i don't see the breakage locally.

**Comment by dr-robertk** [comment]
Hi Markus,

maybe this problem can be fixed with adding -DOPM_COMMON_ROOT manually.
That is what worked for me.

Best,

Rob

On 11/16/2015 06:41 AM, Markus Blatt wrote:
> I just wanted to test my code on another server and used jessie's stock
> dune packages (version 2.3.1) to save time.
> 
> Unfortunately, in opm-material dune-common is not found:
> 
> |-- dune-common_ROOT = /usr/lib/x86_64-linux-gnu/cmake/dune-common CMake
> Error at
> /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136
> (message): Could NOT find dune-common (missing: dune-common_INCLUDE_DIR
> dune-common_LIBRARY) Call Stack (most recent call first):
> /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343
> (_FPHSA_FAILURE_MESSAGE)
> /home/mblatt/DUNE/opm-common/cmake/Modules/OpmPackage.cmake:358
> (find_package_handle_standard_args)
> /home/mblatt/DUNE/opm-common/cmake/Modules/Finddune-common.cmake:14
> (find_opm_package)
> /home/mblatt/DUNE/opm-common/cmake/Modules/OpmFind.cmake:147
> (find_package)
> /home/mblatt/DUNE/opm-common/cmake/Modules/OpmFind.cmake:211
> (find_and_append_package_to)
> /home/mblatt/DUNE/opm-common/cmake/Modules/OpmLibMain.cmake:104
> (find_and_append_package_list_to) CMakeLists.txt:95 (include) --
> Configuring incomplete, errors occurred! |
> 
> The problem is that dunecontrol defines dune-common_ROOT and opm then
> always uses NO_DEFAULT_PATH in its find_... calls
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OPM/opm-common/issues/63>.
> 

-- 

Dr. Robert Kloefkorn           <robert.kloefkorn at iris dot no>

Senior Research Scientist
International Research Institute of Stavanger

Phone: +47 482 93 024


"This e-mail with attached documents is only for the
 addressee indicated above. The e-mail and documents
 may contain  confidential information. If  you are
 not the correct addressee or are responsible for
 transfer of this e-mail with attached documents to
 the correct addressee, any  copying or further
 transfer of information contained herein is expressly
 forbidden. If you have received this e-mail by mistake,
 you are kindly requested to immediately inform me
 thereof by e-mail and delete the e-mail and the
 received documents."

 http://www.iris.no

**Comment by rolk** [comment]
> dropping common paths when _ROOT is set ... some will consider it as the one and only path. OPM seems to have gone with the latter interpretation

Rationale: Say you have $foo at version X as system installation, then you want to check for $foo at version X+1. However, you mistype the directory name, forgot to build it or whatever. If the build system then silently shifts back to using the system version, you will have a long and winding debug process ahead of you, instead of just getting the message up front that whatever you specified ain't gonna happen afterall.

**Comment by blattms** [comment]
Since I cannot reproduce this myself anymore, it must either been a hoax or has been fixed meanwhile.
